# -*- mode: ruby -*-
# vi: set ft=ruby :

$install_ansible = <<-ANSIBLE
  sudo apt install software-properties-common -y
  sudo add-apt-repository --yes --update ppa:ansible/ansible -y
  sudo apt install ansible -y
ANSIBLE

Vagrant.configure("2") do |config|

  if Vagrant.has_plugin? "vagrant-vbguest"
    config.vbguest.no_install  = true
    config.vbguest.auto_update = false
    config.vbguest.no_remote   = true
  end  

  config.vm.define "proxyserver" do | proxyserver |
    proxyserver.vm.box = "bento/ubuntu-22.04"
    proxyserver.vm.hostname = "proxyserver.local.io"
    proxyserver.vm.network "private_network", ip: "172.16.56.3"    
  end

  config.vm.define "node1" do | node1 |
    node1.vm.box = "bento/ubuntu-22.04"
    node1.vm.hostname = "node1.local.io"
    node1.vm.network "private_network", ip: "172.16.56.4"
  end

  config.vm.define "node2" do | node2 |
    node2.vm.box = "bento/ubuntu-22.04"
    node2.vm.hostname = "node2.local.io"
    node2.vm.network "private_network", ip: "172.16.56.5"
  end

  config.vm.define "manager" do  |manager|
    manager.vm.box = "bento/ubuntu-20.04"
    manager.vm.hostname = "manager.local.io"
    manager.vm.network "private_network", ip: "172.16.56.200"

    manager.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "ansible/master-playbook.yml"
      ansible.install        = true
      #ansible.verbose        = true
      ansible.limit          = "all" # or only "nodes" group, etc.
      ansible.inventory_path = "ansible/inventory"
    end
  end

end
